[package]
name = "carolus"
version = "0.1.0"
authors = ["Simon Dickson <simon@simonhdickson.com>"]

[dependencies]
gstreamer = "0.11"
clap = "2.31"
log = "0.4"
simplelog = "0.5"
serde = "1.0"
serde_derive = "1.0"
reqwest = "*"
chrono = "*"
url = "*"
serde_json = "1.0"
failure = "*"
